# Generated by Django 5.1.3 on 2024-11-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Юзернейм')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
                ('uuid', models.CharField(max_length=300, verbose_name='Уникальный идентификатор')),
                ('subscription', models.DateTimeField(verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
