# Generated by Django 5.1.3 on 2024-11-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamarket_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tg_username',
            field=models.CharField(default=1, max_length=200, verbose_name='Тег'),
            preserve_default=False,
        ),
    ]
