# Generated by Django 5.1.3 on 2024-12-19 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamarket_auth', '0002_client_tg_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название приложения')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='tg_username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='client',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yamarket_auth.application', verbose_name='Приложение'),
        ),
    ]
