version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
      - nginx_logs:/var/log/nginx
    ports:
      - "8000:80"
    depends_on:
      - web
    restart: always


volumes:
  postgres_data:
  static_volume:
  nginx_logs:
